//! Strange Attractor Generator.
//!
//! Renders mathematical strange attractors like Peter de Jong and Clifford attractors.
//! These are generated by iterating a set of equations and accumulating hits per pixel,
//! which are then mapped to colors based on density.

use crate::framebuffer::Framebuffer;

/// The type of strange attractor to generate.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AttractorType {
    /// Peter de Jong Attractor.
    /// Equations:
    /// x' = sin(a * y) - cos(b * x)
    /// y' = sin(c * x) - cos(d * y)
    DeJong,
    /// Clifford Attractor.
    /// Equations:
    /// x' = sin(a * y) + c * cos(a * x)
    /// y' = sin(b * x) + d * cos(b * y)
    Clifford,
}

/// Configuration for the Strange Attractor renderer.
#[derive(Debug, Clone, Copy)]
pub struct AttractorConfig {
    /// The type of attractor.
    pub attractor_type: AttractorType,
    /// Parameter 'a' for the equations.
    pub a: f64,
    /// Parameter 'b' for the equations.
    pub b: f64,
    /// Parameter 'c' for the equations.
    pub c: f64,
    /// Parameter 'd' for the equations.
    pub d: f64,
    /// Number of iterations (points to compute).
    pub iterations: u32,
    /// Zoom factor.
    pub zoom: f64,
    /// Color multiplier for density mapping.
    pub color_mult: f32,
    /// Background color.
    pub background_color: u32,
}

impl Default for AttractorConfig {
    fn default() -> Self {
        Self {
            attractor_type: AttractorType::DeJong,
            a: 1.641,
            b: 1.902,
            c: 0.316,
            d: 1.525,
            iterations: 1_000_000,
            zoom: 1.0,
            color_mult: 1.0,
            background_color: 0xFF_000000,
        }
    }
}

/// Renders a strange attractor into the given framebuffer.
pub fn render_attractor(fb: &mut Framebuffer, config: &AttractorConfig) {
    let width = fb.width() as usize;
    let height = fb.height() as usize;

    if width == 0 || height == 0 {
        return;
    }

    // Accumulation buffer for density
    let mut density = vec![0u32; width * height];
    let mut max_density = 1u32;

    let w_f64 = width as f64;
    let h_f64 = height as f64;
    let aspect_ratio = w_f64 / h_f64;

    let mut x = 0.0;
    let mut y = 0.0;

    // Scale down the equations' output to fit the screen
    // The outputs are generally in the range [-2, 2]
    let scale = (h_f64 / 4.0) * config.zoom;
    let cx = w_f64 / 2.0;
    let cy = h_f64 / 2.0;

    for _ in 0..config.iterations {
        let (nx, ny) = match config.attractor_type {
            AttractorType::DeJong => {
                let nx = (config.a * y).sin() - (config.b * x).cos();
                let ny = (config.c * x).sin() - (config.d * y).cos();
                (nx, ny)
            }
            AttractorType::Clifford => {
                let nx = (config.a * y).sin() + config.c * (config.a * x).cos();
                let ny = (config.b * x).sin() + config.d * (config.b * y).cos();
                (nx, ny)
            }
        };

        x = nx;
        y = ny;

        let px = (cx + x * scale) as isize;
        let py = (cy + y * scale) as isize;

        if px >= 0 && px < width as isize && py >= 0 && py < height as isize {
            let idx = (py as usize) * width + (px as usize);
            density[idx] += 1;
            if density[idx] > max_density {
                max_density = density[idx];
            }
        }
    }

    // Map density to color
    let pixels = fb.as_mut_slice();
    let max_density_f32 = (max_density as f32).ln();

    for i in 0..pixels.len() {
        if density[i] > 0 {
            let d = (density[i] as f32).ln() / max_density_f32; // Logarithmic mapping
            let d = (d * config.color_mult).clamp(0.0, 1.0);

            // Simple fire-like gradient
            let r = (d * 255.0) as u32;
            let g = ((d * d) * 255.0) as u32;
            let b = ((d * d * d) * 255.0) as u32;

            pixels[i] = 0xFF_00_00_00 | (r << 16) | (g << 8) | b;
        } else {
            pixels[i] = config.background_color;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_render_attractor_0x0() {
        let mut fb = Framebuffer::new(0, 0).unwrap();
        render_attractor(&mut fb, &AttractorConfig::default());
        assert_eq!(fb.width(), 0);
        assert_eq!(fb.height(), 0);
    }

    #[test]
    fn test_render_attractor_dejong() {
        let mut fb = Framebuffer::new(10, 10).unwrap();
        fb.clear(0xFF_00_00_00);
        let mut config = AttractorConfig::default();
        config.iterations = 100;
        config.background_color = 0xFF_00_00_00;

        render_attractor(&mut fb, &config);

        let mut has_non_black = false;
        for &p in fb.as_slice() {
            if p != 0xFF_00_00_00 {
                has_non_black = true;
                break;
            }
        }
        assert!(
            has_non_black,
            "Framebuffer should not be entirely black after rendering DeJong"
        );
    }

    #[test]
    fn test_render_attractor_clifford() {
        let mut fb = Framebuffer::new(10, 10).unwrap();
        fb.clear(0xFF_00_00_00);
        let mut config = AttractorConfig::default();
        config.attractor_type = AttractorType::Clifford;
        config.iterations = 100;
        config.background_color = 0xFF_00_00_00;

        render_attractor(&mut fb, &config);

        let mut has_non_black = false;
        for &p in fb.as_slice() {
            if p != 0xFF_00_00_00 {
                has_non_black = true;
                break;
            }
        }
        assert!(
            has_non_black,
            "Framebuffer should not be entirely black after rendering Clifford"
        );
    }
}
